name = "bitchless-files"
compatibility_date = "2026-02-01"

# We are using the Dashboard Binding "DB"
# No ID needed here because you set it online.

[vars]
# We are using the Dashboard Variable "ADMIN_PASSWORD"
# No password needed here.
